version: '3.7'
services:
  products:
    image: raphaelmarques84/checkout/products
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: production
      CHOKIDAR_USEPOLLING: true
    volumes:
      - .:/app
      - /app/node_modules

