version: '3.7'
services:
  frontend:
    image: raphaelmarques84/checkout/frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    volumes:
      - ./src:/app/src
      - ./public:/app/public
