FROM node:18-alpine

WORKDIR /app

COPY package*.json .
RUN npm ci

COPY src ./src
COPY public ./public
COPY next.config.mjs .
COPY tsconfig.json .
COPY next-env.d.ts .
COPY postcss.config.js .
COPY tailwind.config.ts .

ENV NEXT_TELEMETRY_DISABLED 1
CMD npm run dev