version: '3.7'
services:
  payments:
    image: raphaelmarques84/checkout/payments
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: production
      CHOKIDAR_USEPOLLING: true
    volumes:
      - .:/app
      - /app/node_modules

